name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: core
        run: npm install

      - name: Start AI Server
        run: python3 ai/ai_server.py &

      - name: Start Middleware
        working-directory: core
        run: npm start &

      - name: Wait for services to start
        run: sleep 10

      - name: Run Tests
        working-directory: core
        run: npm test

      - name: Debug Directory Structure
        run: ls -R
